### ISSUE TITLE
Issue on linux

### ISSUE THREAD

**Issue by generalPanic** [omcaree/node-pololumaestro#3]
# I tried the following code: 

var PololuMaestro = require("pololu-maestro");

//create new instance, specifying control com port
var maestro = new PololuMaestro("/dev/ttyACM0");

//some initial conditions
var pwm = 2000;
var step = -100;
var servoNum = 1;
maestro.on("ready",function(){
//cycle channel 1 indefinitly
maestro.getPosition(servoNum,function(position){console.log("Position: "+position);});

setInterval(function() {
    //reverse direction when limits reached
    if (pwm < 1000 || pwm > 2000) {
        step = -step;
    }

```
//set servo position
pwm+=step;
console.log("setting target to: "+pwm);
maestro.setTarget(servoNum,pwm);
```

}, 200)

});
# 

With no output from Maestro.  Verified that device is working via MaestroControlCenter.  

Node version: v 0.10.12 on  Ubuntu: 3.5.0-36-generic #57-Ubuntu SMP x86_64

**Comment by omcaree** [comment]
Thanks for posting this issue. I'll try to replicate it in the next couple of days (currently don't have access to a Maestro), and get back to you asap.

**Comment by generalPanic** [comment]
Thanks for the wicked fast response.  I found that I'm using it in UART
mode, rather than USB mode...:(  Anyhow, I hope you didn't spend too much
time on it, and thanks for the quick service.

Cheers,
Ben

**Comment by DavidEGrayson** [comment]
Yep, the Serial Mode should be set to "USB Dual Port".  This is not the default setting so people need to open up the Maestro Control Center and change it.
