### ISSUE TITLE
USB dual port mode

### ISSUE THREAD

**Issue by achingbrain** [omcaree/node-pololumaestro#4]
I've pushed branch that adds support for USB dual port mode (see [Serial Settings](http://www.pololu.com/docs/0J40/all#5.a)).

I wanted to have scripts on the Maestro send data back to the host machine but it seems the only way to do it is to connect the TX to the RX pins and use the serial_write_byte command.  The problem is in USB chained serial mode anything sent to the device also gets sent to the TX pin which if it's connected to the RX pin means it gets echoed back to the sender which makes it very confusing, so dual port mode seems the way to go.

Essentially there are now two constructors:

For dual port mode:

``` javascript
new Maestro("COM1", "COM2");
```

and for chained mode:

``` javascript
new Maestro("COM1", 115200);
```

Otherwise the API is unchanged.

I've also added support for generated documentation care of [groc](https://github.com/nevir/groc).  If you run the command `npm run-script docs-publish` they'll get pushed to gh-pages, in the interim you can see an example [here](http://achingbrain.github.io/node-pololumaestro/).

Let me know what you think, or if you'd like me to merge this into master.

Finally, could you make me a maintainer for the NPM pololu-maestro module?

**Comment by omcaree** [comment]
Apologies for my lack of attention, I'm in the middle of a house move and change of careers so things are rather hectic here!

I've not had a chance to look at your changes yet, but I will do over the next few days. In the meantime I have added you as an NPM maintainer, so you should be able to make changes there now.

**Comment by achingbrain** [comment]
No worries, real life does get in the way sometimes..

I've merged this in and pushed an updated module to npm.
