### ISSUE TITLE
warn: SerialPortWrapper Short write! Wrote undefined of 1

### ISSUE THREAD

**Issue by 1am** [omcaree/node-pololumaestro#7]
Hi

I've just tried out your library and it seems that positioning of the servo's via the motor is working great! One thing that i've noticed is that whenever i write anything i get a lot of these in my terminal output:

```
warn: SerialPortWrapper Short write! Wrote undefined of 1
```

It seems that bytesWritten is undefined in serialportwrapper.js.

``` javascript
if(bytesWritten != bytes.length) {
    LOG.warn("SerialPortWrapper", "Short write! Wrote", bytesWritten, "of", bytes.length);
}
```

Is there an easy fix for that?

Best regards

**Comment by omcaree** [comment]
Hi there, thanks for flagging this.

It seems the SerialPort library has been updated and no longer passes the bytesWriten argument to that callback. I have removed this argument and check from the serialportwrapper.js file so you should no longer see this message.
